//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolyoProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioAcunMediaEntities1 : DbContext
    {
        public PortfolioAcunMediaEntities1()
            : base("name=PortfolioAcunMediaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_About> Tbl_About { get; set; }
        public DbSet<Tbl_Category> Tbl_Category { get; set; }
        public DbSet<Tbl_Contact> Tbl_Contact { get; set; }
        public DbSet<Tbl_Educatiton> Tbl_Educatiton { get; set; }
        public DbSet<Tbl_Job> Tbl_Job { get; set; }
        public DbSet<Tbl_Message> Tbl_Message { get; set; }
        public DbSet<Tbl_Project> Tbl_Project { get; set; }
        public DbSet<Tbl_Service> Tbl_Service { get; set; }
        public DbSet<Tbl_Sider> Tbl_Sider { get; set; }
        public DbSet<Tbl_Skill> Tbl_Skill { get; set; }
        public DbSet<Tbl_Testimonial> Tbl_Testimonial { get; set; }
    }
}
